set -g prefix ^A

set -g mouse on # hold shift when selecting

set -g base-index 1              # start indexing windows at 1 instead of 0
set -g renumber-windows on       # renumber all windows when any window is closed
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g set-clipboard on          # use system clipboard
set -g status-position top
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'


# List of plugins
set -g @plugin 'tmux-plugins/tpm' # prefix + I to install plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf' # prefix + F
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @plugin 'tmux-plugins/tmux-yank' # prefix + y
set -g @plugin 'omerxx/tmux-session-manager'
set -g @plugin 'omerxx/tmux-sessionx'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_date_time_text "%H:%M"



bind ^C new-window -c "#{pane_current_path}"
bind ^D detach
bind ^A last-window

bind R source-file ~/.tmux.conf # reload configuration

bind r command-prompt "rename-window %%"

bind z resize-pane -Z
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind '"' split-window -v -c "#{pane_current_path}"
bind "'" split-window -h -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


bind -n F12 send-keys -t ! Up C-m


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

